[build]
  base = "frontend"  # Base directory for the build
  command = "npm run build"
  publish = "build"  # Output directory relative to base
  functions = "../functions"  # Functions directory relative to repo root

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/petsupplies/:splat"
  status = 200