services:
  - type: web
    name: nhanapp-backend
    rootDir: backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: MONGODB_URI
        sync: false

